server:
  port: 8085

spring:
  application:
    name: connector-way4
  cloud:
    consul:
      port: 8500
      discovery:
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        port: 8085