server:
  port: 8090

spring:
  application:
    name: brain
  cloud:
    consul:
      port: 8500
      discovery:
        healthCheckInterval: 5s
        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        port: 8090
